pipeline {
    agent any

    tools {
        maven 'Maven 3.9.11'  // Must match name configured in Jenkins
        jdk 'jdk-21'           // Must match name in Jenkins config
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/sunkuabenay-k/Day-15-10-2025-MyGitTest.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Package') {
            steps {
                bat 'mvn package'
            }
        }

        stage('Deploy to Test Env') {
            steps {
                bat 'deploy\\deploy.bat'
            }
        }
    }
}
